apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume2
  labels:
    type: local
spec:
  storageClassName: manual2
  capacity:
    storage: 33Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data"
